// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2974.PiyushOMatic.subsystems;

import org.usfirst.frc2974.PiyushOMatic.RobotMap;
import org.usfirst.frc2974.PiyushOMatic.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Pneumatics extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	AnalogInput pressureTransducer = RobotMap.pneumaticsPressureTransducer;
	Solenoid claw = RobotMap.pneumaticsClaw;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		setDefaultCommand(new Latch());
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	public double getPressure() {
		/*
		 * 120 psi - 0 psi 5 V - 0 V 120/5 = 24
		 * 24 yields 5.83 = 100 psi
		 * 			 5.74 = 0 psi
		 * -5.74
		 * *100
		 */
		double conversionRate = 1;// TODO verify conversion rate
		return pressureTransducer.getVoltage() * conversionRate;
	}
}
