// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2974.PiyushOMatic;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput driveTrainRightEncoderA;
    public static DigitalInput driveTrainRightEncoderB;
    public static DigitalInput driveTrainLeftEncoderA;
    public static DigitalInput driveTrainLeftEncoderB;
    public static SpeedController driveTrainLeftMainDrive1;
    public static SpeedController driveTrainLeftMainDrive2;
    public static SpeedController driveTrainRightMainDrive1;
    public static SpeedController driveTrainRightMainDrive2;
    public static AnalogInput pneumaticsPressureTransducer;
    public static Solenoid pneumaticsShifter;
    public static Solenoid pneumaticsClaw;
    public static Compressor compressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static DigitalInput digital0;
    public static DigitalInput digital1;
    public static DigitalInput digital2;
    public static DigitalInput digital3;
    public static DigitalInput digital4;
    public static DigitalInput digital5;
    public static DigitalInput digital6;
    public static DigitalInput digital7;
    public static DigitalInput digital8;
    public static DigitalInput digital9;
    
    public static AnalogInput analog0;
    public static AnalogInput analog1;
    public static AnalogInput analog2;
    public static AnalogInput analog3;
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        digital0 = new DigitalInput(0);
        
        driveTrainRightEncoderA = new DigitalInput(1);
        LiveWindow.addSensor("DriveTrain", "Right Encoder A", driveTrainRightEncoderA);
        
        driveTrainRightEncoderB = new DigitalInput(2);
        LiveWindow.addSensor("DriveTrain", "Right Encoder B", driveTrainRightEncoderB);
        
        driveTrainLeftEncoderA = new DigitalInput(3);
        LiveWindow.addSensor("DriveTrain", "Left Encoder A", driveTrainLeftEncoderA);
        
        driveTrainLeftEncoderB = new DigitalInput(4);
        LiveWindow.addSensor("DriveTrain", "Left Encoder B", driveTrainLeftEncoderB);
        


        digital5 = new DigitalInput(5);
        digital6 = new DigitalInput(6);
        digital7 = new DigitalInput(7);
        digital8 = new DigitalInput(8);
        digital9 = new DigitalInput(9);
        
        analog0 = new AnalogInput(0);
        analog1 = new AnalogInput(1);
        analog2 = new AnalogInput(2);

        pneumaticsPressureTransducer = new AnalogInput(3);
        LiveWindow.addSensor("Pneumatics", "Pressure Transducer", pneumaticsPressureTransducer);

        
        driveTrainLeftMainDrive1 = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "Left Main Drive 1", (Talon) driveTrainLeftMainDrive1);
        
        driveTrainLeftMainDrive2 = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "Left Main Drive 2", (Talon) driveTrainLeftMainDrive2);
        
        driveTrainRightMainDrive1 = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "Right Main Drive 1", (Talon) driveTrainRightMainDrive1);
        
        driveTrainRightMainDrive2 = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "Right Main Drive 2", (Talon) driveTrainRightMainDrive2);
        
        
        
        pneumaticsShifter = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "Shifter", pneumaticsShifter);
        
        pneumaticsClaw = new Solenoid(0, 1);
        LiveWindow.addActuator("Pneumatics", "Claw", pneumaticsClaw);
        
        compressor = new Compressor();
        compressor.start();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
